SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[New] (
		[col1]     [int] NULL,
		[col2]     [char](1) COLLATE Cyrillic_General_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[New] SET (LOCK_ESCALATION = TABLE)
GO
